### ISSUE TITLE
Angularjs 2 Fuck

### ISSUE THREAD

**Issue by m2mbr** [du2x/simplenotebook#1]
Angularjs 2 é uma merda. Sai fora disso.

**Comment by du2x** [comment]
Tô curtindo, por enquanto. 
Vou testar o emberjs e o react até o fim do mês.

**Comment by m2mbr** [comment]
React e vuejs https://github.com/vuejs/vue

**Comment by du2x** [comment]
dá uma testada aí depois. tá ficando bacana.

**Comment by m2mbr** [comment]
https://medium.freecodecamp.com/when-should-i-use-typescript-311cb5fe801b
